/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PortraitLazyImport = createFileRoute('/portrait')()
const LandscapeLazyImport = createFileRoute('/landscape')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PortraitLazyRoute = PortraitLazyImport.update({
  path: '/portrait',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/portrait.lazy').then((d) => d.Route))

const LandscapeLazyRoute = LandscapeLazyImport.update({
  path: '/landscape',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/landscape.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/landscape': {
      id: '/landscape'
      path: '/landscape'
      fullPath: '/landscape'
      preLoaderRoute: typeof LandscapeLazyImport
      parentRoute: typeof rootRoute
    }
    '/portrait': {
      id: '/portrait'
      path: '/portrait'
      fullPath: '/portrait'
      preLoaderRoute: typeof PortraitLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LandscapeLazyRoute,
  PortraitLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/landscape",
        "/portrait"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/landscape": {
      "filePath": "landscape.lazy.tsx"
    },
    "/portrait": {
      "filePath": "portrait.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
